name: web_view_service
description: Service and widgets for managing web views in Flutter apps.
version: 1.0.1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  webview_flutter: ^4.0.1
  flutter:
    sdk: flutter
dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
