name: web_view_service
description: Service and widgets for managing web views in Flutter apps.
version: 1.0.2

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  webview_flutter: ^4.0.1
  flutter:
    sdk: flutter
dev_dependencies:
  lints: ^3.0.0
  test: ^1.16.0
